import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import imageLoader from '../imageLoader'
import styles from '../styles/Home.module.scss'
import { Character, GetCharacterResults } from '../types'

const Home: NextPage<{characters: Character[]}> = ({ characters}) => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.title}>
        <h1>
          Rick and Morty
        </h1>
      </div>
      <div className={styles.cardContainer}>
      {characters.map(character => (
        <Link key={character.id.toString()} href="/characters/[id]" as={`/characters/${character.id.toString()}`}>
          <a className={styles.card} key={character.id}>
            <Image
              loader={imageLoader}
              unoptimized
              src={character.image}
              alt={character.name}
              width={300}
              height={300}
            />
            <div className={styles.cardContent}>
              <h3>{character.name}</h3>
              <p>{character.species}</p>
            </div>
          </a>
        </Link>
      ))} 
      </div>
      
    </div>
  )
}

export const getStaticProps:GetStaticProps = async (context) => {
  const res = await fetch('https://rickandmortyapi.com/api/character/')
  const {results}: GetCharacterResults = await res.json()
  return {
    props: {
      characters:results
    }
  }

}

export default Home
